# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Facts
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-wakatime:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Mildly interesting facts
        uses: lowlighter/metrics@latest
        with:
          filename: Output/metrics_facts.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: no
          config_timezone: America/Detroit