# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: base
on:
  # Schedule updates (each hour)
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  workflow_call:
    secrets:
      GH_TOKEN:
        required: true
jobs:
  github-profile:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Profile Update
        uses: lowlighter/metrics@latest
        with:
          user: trentpolack
          template: markdown
          filename: README-dev.output.md
          markdown: >-
            https://raw.githubusercontent.com/trentpolack/trentpolack/main/README-dev.md
          config_output: markdown
          base: header, activity, community, repositories, metadata
          config_timezone: America/New_York
          plugin_activity: yes
          plugin_activity_limit: 7
          plugin_activity_days: 0
          plugin_activity_filter: issue, pr, release, fork, review, ref/create
          plugin_posts: yes
          plugin_posts_source: dev.to
          plugin_posts_descriptions: yes
          plugin_posts_covers: yes
          plugin_posts_limit: 2
          plugin_rss: yes
          plugin_rss_source: https://trentpolack.com/blog?format=rss
          plugin_rss_limit: 4
          plugin_topics: yes
          plugin_topics_limit: 24
          plugin_isocalendar: yes
          plugin_languages: yes
          token: ${{ secrets.GH_TOKEN }}
