name: Wakatime Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '30 18 * * *'
  workflow_dispatch:
jobs:
  waka-readme-stats:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    permissions:
      actions: read
      checks: read
      contents: read
      issues: read
      pull-requests: read 
      repository-projects: read
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
#          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_TOKEN }}
