# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Lines
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-lines:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Plugin Lines
        uses: lowlighter/metrics@latest
        with:
          filename: Output/metrics_lines.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: 
          plugin_lines: yes
          plugin_lines_history_limit: 1
          plugin_lines_repositories_limit: 4
          plugin_lines_sections: base