# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: profile-update
on:
  # Schedule updates (each hour)
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  workflow_call:
    secrets:
      GH_TOKEN:
        required: true
      WAKATIME_API_KEY:
        required: true
jobs:
  github-profile:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Profile Update
        uses: lowlighter/metrics@latest
        with:
          user: trentpolack
          template: markdown
          filename: README-dev.output.md
          markdown: ../../README-dev.md
          config_output: markdown
          config_timezone: America/New_York
          base: header, activity, community, repositories, metadata
          base_indepth: yes
          plugin_activity: yes
          plugin_activity_limit: 7
          plugin_activity_days: 0
          plugin_activity_filter: issue, pr, release, fork, review, ref/create
          plugin_rss: yes
          plugin_rss_source: https://trentpolack.com/blog?format=rss
          plugin_rss_limit: 4
          plugin_topics: yes
          plugin_topics_limit: 24
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_details: lines, bytes-size
          plugin_languages_limit: 4
          plugin_languages_analysis_timeout: 15
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_stars: yes
          plugin_stars_limit: 5
          plugin_wakatime: yes
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
          plugin_wakatime_token: ${{ secrets.WAKATIME_API_KEY }}
          token: ${{ secrets.GH_TOKEN }}