# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Repositories
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-repositories
    permissions:
      contents: write
    steps:
      - name: Plugin Respositories
        uses: lowlighter/metrics@latest
        with:
          filename: metrics_repositories,
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_repositories: yes
          plugin_repositories_order: featured, pinned, starred, random