# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Overview
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-wakatime:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Overview
        uses: lowlighter/metrics@latest
        with:
          filename: Output/overview.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, repositories
          plugin_lines: yes