# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Activity
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-activity:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Plugin Activity
        uses: lowlighter/metrics@latest
        with:
          filename: Output/metrics_activity.svg
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_activity: yes
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_activity_limit: 5
          plugin_activity_load: 300
          plugin_activity_visibility: all
